### ISSUE TITLE
Error: 1: UPnP Error 714 received: Illegal MIME-Type from 192.168.0.38 | 2: UPnP Error 800 received

### ISSUE THREAD

**Issue by wabisabi888** [avantrec/soco-cli#19]
[
[pfninfo.log](https://github.com/avantrec/soco-cli/files/6368653/pfninfo.log)
[version.log](https://github.com/avantrec/soco-cli/files/6368655/version.log)

](url)

The item being played is the entire songs library under My Music (Apple Music)

Other favorites work fine.

**Comment by pwt** [comment]
Hi @wabisabi888:

It's currently not possible to play albums and playlists originating from music services (such as Apple Music) using Sonos Favourites and SoCo-CLI. Single tracks usually work, however.

This is due to limitations in the ability of the underlying SoCo library to play from music services. This issue is being worked on by the SoCo team.

If you want to play albums and playlists from a music service, first add them to a **Sonos Playlist**, then use `add_playlist_to_queue` and `play_from_queue` as described in the [README](https://github.com/avantrec/soco-cli/blob/master/README.md#albums-and-playlists).

**Comment by martin68** [comment]
@pwt Hi, after https://github.com/SoCo/SoCo/pull/883 was merged, this problem still persists, I cannot play favourate albums without adding them to a Sonos Playlist (However, I can play a favourate radio from Apple Music directly).
I am using latest version:
`Successfully installed appdirs-1.4.4 ifaddr-0.2.0 lxml-4.9.1 rangehttpserver-1.2.0 soco-0.28.0 soco-cli-0.4.50 tabulate-0.8.10 xmltodict-0.13.0`
Thank you!

**Comment by pwt** [comment]
There's been no change to SoCo-CLI with regard to this functionality. I consider the recent re-enablement of music service support in SoCo still to be experimental, so I haven't yet added its capabilities to SoCo-CLI.

When/if I do so, the UX will need to change to allow for music service authentication. I have some prototype implementations around this, but haven't settled on a design.

Note that [sharelinks](https://github.com/avantrec/soco-cli#spotify-tidal-deezer-and-apple-music-share-links) can be used to add music service items directly to the queue.
