### ISSUE TITLE
Python on Windows

### ISSUE THREAD

**Issue by apicole** [avantrec/soco-cli#30]
Hi

I tried soco-cli in a raspberry.. worked perfectly
Not used to Python in windows, I have setup the environment and installed the soco-cli package.. 

First I navigate to the Python package repository on my machine..
>> `cd C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages`

From here, I can run 
>>` Python3 discovery.py `
and it outputs my setup.. 

```
Sonos Household: Sonos__xxxxmyuid_

Room/Zone Name    IP Address      Device Model    Visibility    SW Version
----------------  --------------  --------------  ------------  ------------
Anton             192.168.xx.122  One SL          Visible       14.0
Bureau            192.168.xx.108  Play:1          Visible       14.0
Kitchen           192.168.xx.170  One             Visible       14.0
Living Room       192.168.xx.119  Play:1          Visible       14.0
Parents           192.168.xx.176  One             Visible       14.0

1 Sonos Household(s) found
5 Sonos device(s) found

Saved speaker data at: C:\Users\Username/.soco-cli/speakers_v2.pickle
```

But then I try to run sonos SPEAKER play_file myfile.mp3   as I did on the raspbian..
>> `python3 sonos.py Kitchen play_file myfile.mp3`

Output
```
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\soco_cli\sonos.py", line 36, in <module>
    from .wait_actions import process_wait
ImportError: attempted relative import with no known parent package
```
Would you have any idea on how to turn this around ?
Thanks

**Comment by pwt** [comment]
If you've installed SoCo-CLI using `pip`, then you should just be able to use the `sonos` command without specifying the `Python3` executable. The command should be on your path. E.g.:

`C:\Users\Pikasso>sonos Kitchen play_file my file.mp3`

This is because `pip` has installed SoCo-CLI scripts in the `Scripts` directory of your Windows Python installation that allow direct invocation of `sonos` (and other SoCo-CLI commands), and which set up the required environment for the command to run.

The same applies to your Raspberry Pi installation, btw, except the scripts will be in the `bin` directory of your Python installation.

**Comment by apicole** [comment]
Thank you PWT. 
Interestingly, if you install Python as a Windows App from the Microsoft Store, it won't have the same structure.. hence the strange path to my packages and imports.

As a result, I installed Python manually made sure app and script path were included inn my %path% and then.. installed soco-cli.. and ran 
`C:\Users\Username>sonos Kitchen play_file my file.mp3` as on the Pi... 

Problem solved and learned something new ;-)
Havea great day !

**Comment by pzim-devdata** [comment]
It's because the `sonos` command (when you install soco-cli with pip) is not in the same folder as `sonos.py` or `discovery.py`. So there is this error message : `ImportError: attempted relative import with no known parent package` because python doesn't have the good relative address for importing packages when using it from another folder than the folder of the `sonos` command. In the script it is `from sonos import blabla`  for exemple and when using the .py it must be `import blabla` for importing the package blabla. It's a bug from Pypi so we can't use `sonos.py` if we want to use the `sonos` command.

**Comment by pwt** [comment]
> It's a bug from Pypi so we can't use sonos.py if we want to use the sonos command. It's not about the way you install Python, it's about a Pypi bug

I wouldn't consider this a PyPI bug. Mostly, the `pip`/PyPI installs for command line scripts work fine, with issues only presenting when there's something up with the Python installation(s), the virtual environment(s), or the installation steps for the package.

I don't blame people for this -- it's easy to create problems, especially on Windows.
