### ISSUE TITLE
_all_ operator via the web server

### ISSUE THREAD

**Issue by danmcpherson** [avantrec/soco-cli#49]
Quick one I hope. Is the _all_ operator supported by the Web API? I have tried:

http://socoserver/_all_/stop

For example, but it returns "Speaker not found". Let me know, as it's a great shortcut to use in a "good night" automation, or "leaving house".

**Comment by pwt** [comment]
No, not everything is supported when using the HTTP API. The `_all_` speaker shortcut is one of the excluded functions (and is a bit of a hack, really). 

I'll have a think about how to implement similar behaviour when using the HTTP API. It shouldn't be hard to create a new `stop_all` action that stops all speakers in the target speaker's Sonos system.

**Comment by pwt** [comment]
So ... I'd completely forgotten that there is already a `pause_all` action that will work via the HTTP API server. You just need to give it any target speaker name when invoked -- i.e:
```
http://socoserver/speakername/pause_all
```
This will pause playback on all the speakers in the same Sonos system as `speakername`. (Note that the target speaker doesn't need to be playing anything for this to work.)

Since it was just a one-line addition, I've also added a `stop_all` action. This is released in v0.4.58.
