### ISSUE TITLE
Create or modify an alarm with a radio stream always play default CHIME

### ISSUE THREAD

**Issue by Bruno21** [avantrec/soco-cli#50]
Hi,

I tried
```
soco -l Salon create_alarm '10:00,01:30,WEEKDAYS,ON,"http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm",NORMAL,50,OFF'
soco -l Salon modify_alarm 4 '09:45,01:05,WEEKDAYS,YES,"https://icecast.radiofrance.fr/fipjazz-midfi.mp3",SHUFFLE,15,NO'
```
and the alarm play the CHIME

Playing radio stream is fine
```
soco -l Salon play_uri "https://icecast.radiofrance.fr/fipjazz-midfi.mp3"
soco -l Salon play_uri "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm"
```

It worked in the past.

**Comment by pwt** [comment]
Thanks for the report. I'm seeing the same behaviour. I don't think I've changed anything that would cause this, so I wonder if Sonos has made a change.

What Sonos software version are you using?

**Comment by Bruno21** [comment]
```
|  Sonos One            |  Salon               |
| Model name           |  Sonos One           |
| Model number       |  S18                 |
| Serial number        |  xxx:G |
| Player name          |  Salon               |
| Zone name            |  Salon               |
| mac adress           |  xxx  |
| IP address             |  192.168.2.222       |
| Display version      |  15.1.1              |
| Hardware version    |  1.26.1.7-2.2        |
| Software version     |  71.1-38240          |

```

**Comment by pwt** [comment]
Thanks. Same as me. 
Something funny's going on. I'll take a look at this at the weekend.

**Comment by pwt** [comment]
Sorry for the delay in getting to this.

Regrettably, it's clear that Sonos has changed something which has broken this functionality, in both S1 and S2 firmware variants. Possibly it's a bug on their part, possibly it's intentional. Nothing has changed in either SoCo-CLI or in the SoCo alarms module that would explain the issue.

SoCo-CLI and SoCo are sending the correct parameters, receiving a successful response from Sonos, and the alarm is present in the alarms list as I'd expect.

I have a weak suspicion that the lack of metadata supplied with the URI may now be tripping Sonos up, so I'm going to explore that, but I'm not particularly optimistic.

**Comment by pwt** [comment]
Ok, in `v0.4.62` I've changed the way that alarms are created. Instead of using URIs in the alarm specification, the names of Sonos Favourites are used instead.

So, a stream must be present in the Sonos Favourites list before it can be used to create an alarm. Clearly this is an extra step before an alarm can be created, but on the upside it means that any Sonos Favourite can be used as an alarm created by SoCo-CLI.

This has only had light testing, so any feedback is appreciated!

**Comment by pwt** [comment]
Hi @Bruno21 -- did you get a chance to try this?

**Comment by pwt** [comment]
> Sorry @pwt I was very busy this week. With 0.4.62, creating or modify an alarm is fine. It's easy to choose a favorite. I can even choose my Deezer flow. Great work !

Great -- thanks for testing.
