### ISSUE TITLE
Action 'add_uri_to_queue' unlisted in docs

### ISSUE THREAD

**Issue by naxels** [avantrec/soco-cli#6]
Dear maintainers,

Thank you so much for this tool, it's really helpful and saves me time with my custom scripts :)

Before switching to this app,
A feature that I often used in my custom script is add_uri_to_queue, found in SoCo Github repo, docs here:
https://soco.readthedocs.io/en/latest/api/soco.core.html?highlight=_uri#soco.core.SoCo.add_uri_to_queue

I was unable to find this in the README.md however it does work and is in the action_processor.py

Could you document this feature as it really helps me with creating a daily URI playlist for Sonos and might help others as well.

Thank you!

**Comment by pwt** [comment]
Hi -- thanks for the feedback. Glad you're finding it useful.

I'd actually forgotten I'd implemented a wrapper for `add_uri_to_queue`. In v0.1.52, I've updated the action so that it can optionally be followed with a queue position (an integer, or 'next' to play as the next track), and it now returns the queue position at which the URI has been inserted. I've added it to the documentation.
