### ISSUE TITLE
Is it really neccessary that the HTTP server must be in the same subnet as the sonos speeakers?

### ISSUE THREAD

**Issue by stax0** [avantrec/soco-cli#71]
Hi,
my speakers are seperated in an IOT vlan, and I want to use soco-cli.

From network side, everthing is setup correctly and I can reach and find all the speakers although they are in a different network than my smartphone for example.

After playing arround with soco-cli play_file commands, I noticed that it does not work properly because soco-cli is trying to find an ip address in the same address range as the speakers for spinning up the http server.

My question is: is this limitation really necessary? 

https://github.com/avantrec/soco-cli/blob/250c83f9e2458b099e9f400880d054f76af053d5/soco_cli/play_local_file.py#L135C63-L135C63

Thanks in advance

**Comment by pwt** [comment]
In SoCo-CLI `v0.4.74` I've changed the algorithm used to determine the interface/IP address on which to host the HTTP server for `play_file`. It now uses a target speaker reachability test instead of a network IP match. This is slower, but the difference is probably negligible in general use.

Let me know if this works for your network setup.

**Comment by stax0** [comment]
I really appreciate the change.
Works like a charm

Thank you
